apiVersion: v1
kind: Service	
metadata:
  name: pma-svc
  labels:
    app: pma-app
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: pma-app
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: pma-port
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
spec:
  selector:
    matchLabels:
      app: pma-app
  template:
    metadata:
      name: pma-pod
      labels:
        app: pma-app
    spec:
      containers:
      - name: pma-container
        image: pma-local
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: pma-port
