apiVersion: v1
kind: Service	
metadata:
  name: nginx-svc
  labels:
    app: nginx-app
#  annotations:
#    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
#  loadBalancerIP: 192.168.49.4
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
