apiVersion: v1
kind: Service	
metadata:
  name: grafana-svc
  labels:
    app: grafana-app
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: grafana-app
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: grafana-port
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana-container
        image: grafana-local
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana-port
