apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influxdb-app
spec:
  ports:
    - port: 8086
      targetPort: 8086
      name: influxdb-port
      protocol: TCP
  selector:
    app: influxdb-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-claim
  labels:
    app: influxdb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb-app
spec:
  selector:
    matchLabels:
      app: influxdb-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      containers:
      - image: influxdb-local
        name: influxdb-container
        imagePullPolicy: Never
        livenessProbe:
          exec:
           command:
           - sh
           - /srcs/probe.sh
          initialDelaySeconds: 30
          periodSeconds: 5
        env:
        ports:
        - containerPort: 8086
          name: influxdb-port
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-claim
