apiVersion: v1
kind: Service	
metadata:
  name: pma-svc
  labels:
    app: pma-app
  annotations:
    metallb.universe.tf/allow-shared-ip: share-ip
spec:
  selector:
    app: pma-app
  type: LoadBalancer
  loadBalancerIP: None
  ports:
  - name: pma
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
spec:
  selector:
    matchLabels:
      app: pma-app
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      name: pma-pod
      labels:
        app: pma-app
    spec:
      containers:
      - name: pma
        image: pma-local
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: pma
