apiVersion: v1
kind: Service	
metadata:
  name: ftps-svc
  labels:
    app: ftps-app
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps-app
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: ftps-port
    protocol: TCP
    port: 21
    targetPort: 21
  - name: ftps-return
    port: 20
    targetPort: 20
  - name: ftps-pass1
    port: 21001
    targetPort: 21001
  - name: ftps-pass2
    port: 21002
    targetPort: 21002
  - name: ftps-pass3
    port: 21003
    targetPort: 21003
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-claim
  labels:
    app: ftps-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps-app
    spec:
      containers:
      - name: ftps-container
        image: ftps-local
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps-port
        - containerPort: 20
          name: ftps-return
        - containerPort: 21001
          name: ftps-pass1
        - containerPort: 21002
          name: ftps-pass2
        - containerPort: 21003
          name: ftps-pass3
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /home/ftp
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-claim
