apiVersion: v1
kind: Service	
metadata:
  name: nginx-svc
  labels:
    app: nginx-app
#  annotations:
#    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
#  loadBalancerIP: 192.168.49.4
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx-local
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
