apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql-app
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql-port
      protocol: TCP
  selector:
    app: mysql-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
  labels:
    app: mysql-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql-app
spec:
  selector:
    matchLabels:
      app: mysql-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - image: mysql-local
        name: mysql
        imagePullPolicy: Never
        livenessProbe:
          exec:
           command:
           - sh
           - /srcs/probe.sh
          initialDelaySeconds: 30
          periodSeconds: 5
        startupProbe:
          exec:
           command: ["/bin/sh", "-c", "stat /var/lib/mysql/init.beacon"]
          initialDelaySeconds: 15
          failureThreshold: 10
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-claim
