apiVersion: v1
kind: Service	
metadata:
  name: nginx-svc
  labels:
    app: nginx-app
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx-local
        imagePullPolicy: Never
        livenessProbe:
          exec:
           command:
           - sh
           - /srcs/probe.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
