CREATE USER 'my-user'@'%' IDENTIFIED BY 'my-pass';
GRANT ALL PRIVILEGES ON *.* TO 'my-user'@'%'WITH GRANT OPTION;
CREATE DATABASE wordpress;
CREATE USER 'wp-user'@'%' IDENTIFIED BY 'wp-pass';
GRANT ALL PRIVILEGES ON wordpress.* TO 'wp-user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
