GRANT ALL PRIVILEGES ON *.* TO 'my-user' IDENTIFIED BY 'my-pass' WITH GRANT OPTION;
CREATE DATABASE wordpress;
GRANT ALL PRIVILEGES ON wordpress.* TO 'wp-user' IDENTIFIED BY 'wp-pass' WITH GRANT OPTION;
