apiVersion: v1
kind: Service	
metadata:
  name: wordpress-svc
  labels:
    app: wordpress-app
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress-app
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    protocol: TCP
    port: 5050
    targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress
        image: wordpress-local
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wordpress
